language: node_js
node_js:
  - node

install:
  - npm i -g serverless
  - npm i --no-optional

cache:
  - directories: node_modules
    
script:
  - chmod +x ./.travis-deploy.sh
  - ./.travis-deploy.sh
