service: ractivitytracker

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  environment:
    ACTIVITIES_TABLE: { Ref: ActivitiesTable }
    STAGE: ${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:dynamodb:'
            - Ref: AWS::Region
            - ':'
            - Ref: AWS::AccountId
            - ':table/'
            - Ref: ActivitiesTable
            - '*'

functions:

  postMessage:
    handler: functions/postMessage.handler
    events:
      - http:
          path: activities
          method: post
          cors: true

  getMessage:
    handler: functions/getMessage.handler
    events:
      - http:
          path: activities
          method: get
          cors: true

resources:

  Resources:

    ActivitiesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: RBActivities
        AttributeDefinitions:
          - AttributeName: activityId
            AttributeType: S
          - AttributeName: activityDate
            AttributeType: S
        KeySchema:
          - AttributeName: activityId
            KeyType: HASH
          - AttributeName: activityDate
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  Outputs:

    ActivitiesTable:
      Description: Relationship Activity Tracker
      Value: { Ref: ActivitiesTable }
      Export:
        Name: ${opt:stage, self:provider.stage}-ActivitiesTable
