service: ractivitytracker-api

provider:
  name: aws
  runtime: nodejs4.3
  stage: local
  environment:
    ACTIVITIES_TABLE: { Ref: ActivitiesTable }
    STAGE: ${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:dynamodb:'
            - Ref: AWS::Region
            - ':'
            - Ref: AWS::AccountId
            - ':table/'
            - Ref: ActivitiesTable
            - '*'
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: '*'

functions:

  postMessage:
    handler: functions/postMessage.handler
    events:
      - http:
          path: functions
          method: post
          cors: true

  getMessage:
    handler: functions/getMessage.handler
    events:
      - http:
          path: functions
          method: get
          cors: true

resources:

  Resources:

    GroupsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: activityId
            AttributeType: S
          - AttributeName: activityDate
            AttributeType: S
          - AttributeName: activitySource
            AttributeType: S
          - AttributeName: activityWith
            AttributeType: S
          - AttributeName: activityType
            AttributeType: S
        KeySchema:
          - AttributeName: activityId
            KeyType: HASH
          - AttributeName: activityDate
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  Outputs:

    ActivitiesTable:
      Description: Name of the Activities table for the ${opt:stage, self:provider.stage} stage
      Value: { Ref: ActivitiesTable }
      Export:
        Name: ${opt:stage, self:provider.stage}-ActivitiesTable
