service: ractivitytracker

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  environment:
    ACTIVITIES_TABLE: { Ref: ActivitiesTable }
    STAGE: ${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:dynamodb:'
            - Ref: AWS::Region
            - ':'
            - Ref: AWS::AccountId
            - ':table/'
            - Ref: ActivitiesTable
            - '*'
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: '*'

functions:

  postMessage:
    handler: activities/postMessage/postMessage.handler
    events:
      - http:
          path: functions
          method: post
          cors: true

  dynoToCsv:
    handler: activities/dynoToCsv.handler
    events:
      - http:
<<<<<<< HEAD
          path: functions
          method: post
=======
          path: activities
          method: get
>>>>>>> origin/master
          cors: true

resources:

  Resources:
    BucketResource:
      Type: "AWS::S3::Bucket"

    ActivitiesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Activities
        AttributeDefinitions:
          - AttributeName: timestamp
            AttributeType: S
          - AttributeName: userName
            AttributeType: S
        KeySchema:
          - AttributeName: timestamp
            KeyType: HASH
          - AttributeName: userName
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  Outputs:

    ActivitiesTable:
      Description: Relationship Activity Tracker
      Value: { Ref: ActivitiesTable }
      Export:
        Name: ${opt:stage, self:provider.stage}-ActivitiesTable
